// Shared proto contract for host(Rust) <-> sidecar(Go) gRPC traffic.
//
// This directory is the single source of truth for the gRPC wire format,
// consumed by both the Go sidecar (via protoc, see
// sidecar/grpc/kubecontextpb) and the Rust host (via tonic-build, see
// src-tauri/build.rs). It deliberately sits at the repo root, outside the
// Go module, mirroring the layout in ~/workspace/kubetail.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: kubecontext.proto

package kubecontextpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchRequest) Reset() {
	*x = WatchRequest{}
	mi := &file_kubecontext_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchRequest) ProtoMessage() {}

func (x *WatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kubecontext_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchRequest.ProtoReflect.Descriptor instead.
func (*WatchRequest) Descriptor() ([]byte, []int) {
	return file_kubecontext_proto_rawDescGZIP(), []int{0}
}

// KubeContextState is a full snapshot of the parts of the kubeconfig the host
// cares about. Every Watch message carries the complete current state.
type KubeContextState struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CurrentContext string                 `protobuf:"bytes,1,opt,name=current_context,json=currentContext,proto3" json:"current_context,omitempty"`
	Contexts       []*Context             `protobuf:"bytes,2,rep,name=contexts,proto3" json:"contexts,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *KubeContextState) Reset() {
	*x = KubeContextState{}
	mi := &file_kubecontext_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KubeContextState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KubeContextState) ProtoMessage() {}

func (x *KubeContextState) ProtoReflect() protoreflect.Message {
	mi := &file_kubecontext_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KubeContextState.ProtoReflect.Descriptor instead.
func (*KubeContextState) Descriptor() ([]byte, []int) {
	return file_kubecontext_proto_rawDescGZIP(), []int{1}
}

func (x *KubeContextState) GetCurrentContext() string {
	if x != nil {
		return x.CurrentContext
	}
	return ""
}

func (x *KubeContextState) GetContexts() []*Context {
	if x != nil {
		return x.Contexts
	}
	return nil
}

type Context struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Context) Reset() {
	*x = Context{}
	mi := &file_kubecontext_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Context) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Context) ProtoMessage() {}

func (x *Context) ProtoReflect() protoreflect.Message {
	mi := &file_kubecontext_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Context.ProtoReflect.Descriptor instead.
func (*Context) Descriptor() ([]byte, []int) {
	return file_kubecontext_proto_rawDescGZIP(), []int{2}
}

func (x *Context) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type SetCurrentContextRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetCurrentContextRequest) Reset() {
	*x = SetCurrentContextRequest{}
	mi := &file_kubecontext_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetCurrentContextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetCurrentContextRequest) ProtoMessage() {}

func (x *SetCurrentContextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kubecontext_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetCurrentContextRequest.ProtoReflect.Descriptor instead.
func (*SetCurrentContextRequest) Descriptor() ([]byte, []int) {
	return file_kubecontext_proto_rawDescGZIP(), []int{3}
}

func (x *SetCurrentContextRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type SetCurrentContextResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetCurrentContextResponse) Reset() {
	*x = SetCurrentContextResponse{}
	mi := &file_kubecontext_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetCurrentContextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetCurrentContextResponse) ProtoMessage() {}

func (x *SetCurrentContextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kubecontext_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetCurrentContextResponse.ProtoReflect.Descriptor instead.
func (*SetCurrentContextResponse) Descriptor() ([]byte, []int) {
	return file_kubecontext_proto_rawDescGZIP(), []int{4}
}

var File_kubecontext_proto protoreflect.FileDescriptor

const file_kubecontext_proto_rawDesc = "" +
	"\n" +
	"\x11kubecontext.proto\x12\vkubecontext\"\x0e\n" +
	"\fWatchRequest\"m\n" +
	"\x10KubeContextState\x12'\n" +
	"\x0fcurrent_context\x18\x01 \x01(\tR\x0ecurrentContext\x120\n" +
	"\bcontexts\x18\x02 \x03(\v2\x14.kubecontext.ContextR\bcontexts\"\x1d\n" +
	"\aContext\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\".\n" +
	"\x18SetCurrentContextRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x1b\n" +
	"\x19SetCurrentContextResponse2\xbd\x01\n" +
	"\x12KubeContextService\x12C\n" +
	"\x05Watch\x12\x19.kubecontext.WatchRequest\x1a\x1d.kubecontext.KubeContextState0\x01\x12b\n" +
	"\x11SetCurrentContext\x12%.kubecontext.SetCurrentContextRequest\x1a&.kubecontext.SetCurrentContextResponseB?Z=github.com/kubetail-org/kstack-app/sidecar/grpc/kubecontextpbb\x06proto3"

var (
	file_kubecontext_proto_rawDescOnce sync.Once
	file_kubecontext_proto_rawDescData []byte
)

func file_kubecontext_proto_rawDescGZIP() []byte {
	file_kubecontext_proto_rawDescOnce.Do(func() {
		file_kubecontext_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kubecontext_proto_rawDesc), len(file_kubecontext_proto_rawDesc)))
	})
	return file_kubecontext_proto_rawDescData
}

var file_kubecontext_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_kubecontext_proto_goTypes = []any{
	(*WatchRequest)(nil),              // 0: kubecontext.WatchRequest
	(*KubeContextState)(nil),          // 1: kubecontext.KubeContextState
	(*Context)(nil),                   // 2: kubecontext.Context
	(*SetCurrentContextRequest)(nil),  // 3: kubecontext.SetCurrentContextRequest
	(*SetCurrentContextResponse)(nil), // 4: kubecontext.SetCurrentContextResponse
}
var file_kubecontext_proto_depIdxs = []int32{
	2, // 0: kubecontext.KubeContextState.contexts:type_name -> kubecontext.Context
	0, // 1: kubecontext.KubeContextService.Watch:input_type -> kubecontext.WatchRequest
	3, // 2: kubecontext.KubeContextService.SetCurrentContext:input_type -> kubecontext.SetCurrentContextRequest
	1, // 3: kubecontext.KubeContextService.Watch:output_type -> kubecontext.KubeContextState
	4, // 4: kubecontext.KubeContextService.SetCurrentContext:output_type -> kubecontext.SetCurrentContextResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_kubecontext_proto_init() }
func file_kubecontext_proto_init() {
	if File_kubecontext_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kubecontext_proto_rawDesc), len(file_kubecontext_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kubecontext_proto_goTypes,
		DependencyIndexes: file_kubecontext_proto_depIdxs,
		MessageInfos:      file_kubecontext_proto_msgTypes,
	}.Build()
	File_kubecontext_proto = out.File
	file_kubecontext_proto_goTypes = nil
	file_kubecontext_proto_depIdxs = nil
}
