// Shared proto contract for host(Rust) <-> sidecar(Go) gRPC traffic.
//
// This directory is the single source of truth for the gRPC wire format,
// consumed by both the Go sidecar (via protoc, see
// sidecar/grpc/kubecontextpb) and the Rust host (via tonic-build, see
// src-tauri/build.rs). It deliberately sits at the repo root, outside the
// Go module, mirroring the layout in ~/workspace/kubetail.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: kubecontext.proto

package kubecontextpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	KubeContextService_Watch_FullMethodName             = "/kubecontext.KubeContextService/Watch"
	KubeContextService_SetCurrentContext_FullMethodName = "/kubecontext.KubeContextService/SetCurrentContext"
)

// KubeContextServiceClient is the client API for KubeContextService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// KubeContextService is the host-internal control channel for the kubeconfig
// current-context. It rides the same socket as GraphQL (h2c multiplexing) but
// is consumed only by the native host (the tray), never the webview — the
// webview keeps using the GraphQL kubeConfigWatch/setCurrentContext surface.
// Both transports share the one KubeConfigWatcher, so a change made through
// either is observed by the other.
type KubeContextServiceClient interface {
	// Watch streams the kubeconfig context state: one full snapshot immediately,
	// then a new full snapshot on every on-disk change. Long-lived; the stream
	// ends when the client cancels or the sidecar shuts down.
	Watch(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[KubeContextState], error)
	// SetCurrentContext persists `name` as the kubeconfig current-context
	// (kubectl-visible). The resulting change is also delivered to any active
	// Watch stream. Errors with InvalidArgument for an empty/unknown name.
	SetCurrentContext(ctx context.Context, in *SetCurrentContextRequest, opts ...grpc.CallOption) (*SetCurrentContextResponse, error)
}

type kubeContextServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewKubeContextServiceClient(cc grpc.ClientConnInterface) KubeContextServiceClient {
	return &kubeContextServiceClient{cc}
}

func (c *kubeContextServiceClient) Watch(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[KubeContextState], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &KubeContextService_ServiceDesc.Streams[0], KubeContextService_Watch_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchRequest, KubeContextState]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type KubeContextService_WatchClient = grpc.ServerStreamingClient[KubeContextState]

func (c *kubeContextServiceClient) SetCurrentContext(ctx context.Context, in *SetCurrentContextRequest, opts ...grpc.CallOption) (*SetCurrentContextResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetCurrentContextResponse)
	err := c.cc.Invoke(ctx, KubeContextService_SetCurrentContext_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KubeContextServiceServer is the server API for KubeContextService service.
// All implementations must embed UnimplementedKubeContextServiceServer
// for forward compatibility.
//
// KubeContextService is the host-internal control channel for the kubeconfig
// current-context. It rides the same socket as GraphQL (h2c multiplexing) but
// is consumed only by the native host (the tray), never the webview — the
// webview keeps using the GraphQL kubeConfigWatch/setCurrentContext surface.
// Both transports share the one KubeConfigWatcher, so a change made through
// either is observed by the other.
type KubeContextServiceServer interface {
	// Watch streams the kubeconfig context state: one full snapshot immediately,
	// then a new full snapshot on every on-disk change. Long-lived; the stream
	// ends when the client cancels or the sidecar shuts down.
	Watch(*WatchRequest, grpc.ServerStreamingServer[KubeContextState]) error
	// SetCurrentContext persists `name` as the kubeconfig current-context
	// (kubectl-visible). The resulting change is also delivered to any active
	// Watch stream. Errors with InvalidArgument for an empty/unknown name.
	SetCurrentContext(context.Context, *SetCurrentContextRequest) (*SetCurrentContextResponse, error)
	mustEmbedUnimplementedKubeContextServiceServer()
}

// UnimplementedKubeContextServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedKubeContextServiceServer struct{}

func (UnimplementedKubeContextServiceServer) Watch(*WatchRequest, grpc.ServerStreamingServer[KubeContextState]) error {
	return status.Error(codes.Unimplemented, "method Watch not implemented")
}
func (UnimplementedKubeContextServiceServer) SetCurrentContext(context.Context, *SetCurrentContextRequest) (*SetCurrentContextResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetCurrentContext not implemented")
}
func (UnimplementedKubeContextServiceServer) mustEmbedUnimplementedKubeContextServiceServer() {}
func (UnimplementedKubeContextServiceServer) testEmbeddedByValue()                            {}

// UnsafeKubeContextServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KubeContextServiceServer will
// result in compilation errors.
type UnsafeKubeContextServiceServer interface {
	mustEmbedUnimplementedKubeContextServiceServer()
}

func RegisterKubeContextServiceServer(s grpc.ServiceRegistrar, srv KubeContextServiceServer) {
	// If the following call panics, it indicates UnimplementedKubeContextServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&KubeContextService_ServiceDesc, srv)
}

func _KubeContextService_Watch_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(KubeContextServiceServer).Watch(m, &grpc.GenericServerStream[WatchRequest, KubeContextState]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type KubeContextService_WatchServer = grpc.ServerStreamingServer[KubeContextState]

func _KubeContextService_SetCurrentContext_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetCurrentContextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KubeContextServiceServer).SetCurrentContext(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KubeContextService_SetCurrentContext_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KubeContextServiceServer).SetCurrentContext(ctx, req.(*SetCurrentContextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// KubeContextService_ServiceDesc is the grpc.ServiceDesc for KubeContextService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KubeContextService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kubecontext.KubeContextService",
	HandlerType: (*KubeContextServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetCurrentContext",
			Handler:    _KubeContextService_SetCurrentContext_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Watch",
			Handler:       _KubeContextService_Watch_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "kubecontext.proto",
}
