// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graph

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
)

type Mutation struct {
}

type Query struct {
}

// User-scoped preferences synced through the kstack cloud. Today this is a single free-form `placeholder` string — extend as the product grows.
type Settings struct {
	Placeholder string `json:"placeholder"`
}

type Subscription struct {
}

// Connection/sync health of the always-on engine that owns the single upstream connection.
type SyncStatus struct {
	// Engine lifecycle state.
	State SyncState `json:"state"`
	// Last upstream error; empty string when healthy.
	LastError string `json:"lastError"`
	// Unix-millis of the last successful snapshot reconcile; 0 if never synced.
	LastSyncedAt int `json:"lastSyncedAt"`
	// Unix-millis of the next scheduled reconnect while in `backoff`; 0 otherwise.
	RetryAt int `json:"retryAt"`
}

type UpdateSettingsInput struct {
	Placeholder *string `json:"placeholder,omitempty"`
}

// Engine connection lifecycle.
type SyncState string

const (
	SyncStateConnecting SyncState = "CONNECTING"
	SyncStateLive       SyncState = "LIVE"
	SyncStateBackoff    SyncState = "BACKOFF"
	SyncStateOffline    SyncState = "OFFLINE"
)

var AllSyncState = []SyncState{
	SyncStateConnecting,
	SyncStateLive,
	SyncStateBackoff,
	SyncStateOffline,
}

func (e SyncState) IsValid() bool {
	switch e {
	case SyncStateConnecting, SyncStateLive, SyncStateBackoff, SyncStateOffline:
		return true
	}
	return false
}

func (e SyncState) String() string {
	return string(e)
}

func (e *SyncState) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SyncState(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SyncState", str)
	}
	return nil
}

func (e SyncState) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *SyncState) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e SyncState) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
