package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"fmt"
	"time"

	anthropic "github.com/anthropics/anthropic-sdk-go"
	"github.com/kubetail-org/kstack-app/sidecar/server/graph/model"
)

// AuthInfos is the resolver for the authInfos field.
func (r *kubeConfigResolver) AuthInfos(ctx context.Context, obj *model.KubeConfig) ([]*model.KubeConfigAuthInfo, error) {
	outList := make([]*model.KubeConfigAuthInfo, 0, len(obj.Config.AuthInfos))
	for name, val := range obj.Config.AuthInfos {
		outList = append(outList, &model.KubeConfigAuthInfo{AuthInfo: val, Name: name})
	}
	return outList, nil
}

// Clusters is the resolver for the clusters field.
func (r *kubeConfigResolver) Clusters(ctx context.Context, obj *model.KubeConfig) ([]*model.KubeConfigCluster, error) {
	outList := make([]*model.KubeConfigCluster, 0, len(obj.Config.Clusters))
	for name, val := range obj.Config.Clusters {
		outList = append(outList, &model.KubeConfigCluster{Cluster: val, Name: name})
	}
	return outList, nil
}

// Contexts is the resolver for the contexts field.
func (r *kubeConfigResolver) Contexts(ctx context.Context, obj *model.KubeConfig) ([]*model.KubeConfigContext, error) {
	outList := make([]*model.KubeConfigContext, 0, len(obj.Config.Contexts))
	for name, val := range obj.Config.Contexts {
		outList = append(outList, &model.KubeConfigContext{Context: val, Name: name})
	}
	return outList, nil
}

// UpdateSettings is the resolver for the updateSettings field.
// Write-through: push to the cloud, then publish to the shared Hub so
// active subscribers update immediately. Persistence is intentionally NOT
// done here — the engine is the sole syncstore writer; it persists this
// change when the cloud echoes it back on its stream (single-writer keeps
// the engine's version/mirror coherent). Read-after-write via the
// `settings` query may briefly lag, but the UI consumes `settingsWatch`,
// which the Hub publish satisfies at once.
func (r *mutationResolver) UpdateSettings(ctx context.Context, input model.UpdateSettingsInput) (*model.Settings, error) {
	ci := cloudInput(input)
	out, err := r.Cloud.UpdateSettings(ctx, bearer(ctx), ci)
	if err != nil {
		// Offline/transient: persist (coalesced) so the engine replays
		// it on its next Live. Still surface the error — the client
		// must know it hasn't reached the cloud yet.
		if qErr := r.Queue.Enqueue(ci); qErr != nil {
			return nil, fmt.Errorf("%w (also failed to queue: %v)", err, qErr)
		}
		return nil, err
	}
	r.Hub.Publish(out)
	return toGraphSettings(out), nil
}

// Ping is the resolver for the ping field.
func (r *queryResolver) Ping(ctx context.Context) (string, error) {
	return "pong", nil
}

// Settings is the resolver for the settings field. Served entirely from
// the engine-maintained syncstore — the engine owns the only cloud
// connection, so reads never touch the network. An empty store (engine
// never synced, e.g. logged out) yields the zero value, not an error.
func (r *queryResolver) Settings(ctx context.Context) (*model.Settings, error) {
	env, err := r.Store.Load()
	if err != nil {
		return nil, err
	}
	return toGraphSettings(env.Data), nil
}

// SyncStatus is the resolver for the syncStatus field.
func (r *queryResolver) SyncStatus(ctx context.Context) (*model.SyncStatus, error) {
	return toGraphSyncStatus(r.Sync.Status()), nil
}

// Tick is the resolver for the tick field. Streams 1, 2, 3, … on the
// configured interval. Cancellation comes from the gqlgen runtime when the
// client unsubscribes (or the WebSocket closes).
func (r *subscriptionResolver) Tick(ctx context.Context) (<-chan int, error) {
	ch := make(chan int, 1)
	go func() {
		defer close(ch)
		t := time.NewTicker(tickInterval())
		defer t.Stop()
		for n := 1; ; n++ {
			select {
			case <-ctx.Done():
				return
			case <-t.C:
			}
			select {
			case ch <- n:
			case <-ctx.Done():
				return
			}
		}
	}()
	return ch, nil
}

// SettingsWatch is the resolver for the settingsWatch field. Subscribes
// the shared Hub only — the engine is the single upstream consumer and
// fans cloud changes (plus mutation publishes) through this Hub. A new
// subscriber gets the current syncstore snapshot first so it doesn't have
// to wait for the next change, then live Hub deltas.
func (r *subscriptionResolver) SettingsWatch(ctx context.Context) (<-chan *model.Settings, error) {
	hubCh, unsub := r.Hub.Subscribe()
	return streamWithSnapshot(ctx, hubCh, unsub, toGraphSettings, func() (*model.Settings, bool) {
		// A failed load (e.g. nothing persisted yet) is non-fatal here:
		// ok=false skips the snapshot (see streamWithSnapshot's doc).
		env, err := r.Store.Load()
		if err != nil {
			return nil, false
		}
		return toGraphSettings(env.Data), true
	}), nil
}

// SyncStatusWatch is the resolver for the syncStatusWatch field. Emits
// the current status immediately (so a new subscriber doesn't wait for the
// next transition), then every subsequent transition from the engine.
func (r *subscriptionResolver) SyncStatusWatch(ctx context.Context) (<-chan *model.SyncStatus, error) {
	sub, unsub := r.Sync.WatchStatus()
	return streamWithSnapshot(ctx, sub, unsub, toGraphSyncStatus, func() (*model.SyncStatus, bool) {
		return toGraphSyncStatus(r.Sync.Status()), true
	}), nil
}

// ChatStream is the resolver for the chatStream field. POC: forwards the
// conversation to Anthropic and streams the assistant's reply token-by-token.
// Emits `{delta, done:false}` per text chunk and a final `{delta:"", done:true}`
// frame so the client can tear down without the subscribe-exchange treating
// the channel close as a transport drop (which would trigger reconnect).
func (r *subscriptionResolver) ChatStream(ctx context.Context, input model.ChatInput) (<-chan *model.ChatChunk, error) {
	msgs := make([]anthropic.MessageParam, 0, len(input.Messages))
	for _, m := range input.Messages {
		block := anthropic.NewTextBlock(m.Content)
		if m.Role == "assistant" {
			msgs = append(msgs, anthropic.NewAssistantMessage(block))
		} else {
			msgs = append(msgs, anthropic.NewUserMessage(block))
		}
	}
	ch := make(chan *model.ChatChunk)
	go func() {
		defer close(ch)
		emit := func(c *model.ChatChunk) bool {
			select {
			case ch <- c:
				return true
			case <-ctx.Done():
				return false
			}
		}
		client := anthropic.NewClient()
		stream := client.Messages.NewStreaming(ctx, anthropic.MessageNewParams{
			Model:     anthropic.ModelClaudeHaiku4_5,
			MaxTokens: 1024,
			Messages:  msgs,
			Tools: []anthropic.ToolUnionParam{
				{OfWebSearchTool20250305: &anthropic.WebSearchTool20250305Param{}},
				{OfWebFetchTool20260309: &anthropic.WebFetchTool20260309Param{}},
			},
		})
		for stream.Next() {
			evt := stream.Current()
			if d, ok := evt.AsAny().(anthropic.ContentBlockDeltaEvent); ok {
				if td, ok := d.Delta.AsAny().(anthropic.TextDelta); ok && td.Text != "" {
					if !emit(&model.ChatChunk{Delta: td.Text, Done: false}) {
						return
					}
				}
			}
		}
		if err := stream.Err(); err != nil {
			emit(&model.ChatChunk{Delta: "error: " + err.Error(), Done: true})
		} else {
			emit(&model.ChatChunk{Delta: "", Done: true})
		}
		// Keep the channel open until the client unsubscribes. If we
		// returned here, gqlgen would emit a `complete` frame and the
		// subscribe-exchange would treat it as a transport drop —
		// flashing a "Subscription dropped" banner before the client's
		// pause-driven unsubscribe lands. ctx.Done() fires the moment
		// the client tears down, so the goroutine still cleans up
		// promptly.
		<-ctx.Done()
	}()
	return ch, nil
}

// KubeConfigWatch is the resolver for the kubeConfigWatch field. The
// first frame is ADDED with whatever the watcher's hub currently holds
// (seeded with the loaded config at NewKubeConfigWatcher); subsequent
// frames are MODIFIED, one per reload. Defensive nil-skip in case the
// hub ever publishes a nil slot.
func (r *subscriptionResolver) KubeConfigWatch(ctx context.Context) (<-chan *model.KubeConfigWatchEvent, error) {
	if r.KubeConfigWatcher == nil {
		// Parallels noopStatus / closed-channel defaults the rest of
		// NewHandler installs: a Config{} handler must not panic on
		// kubeConfigWatch — stream nothing, end immediately.
		ch := make(chan *model.KubeConfigWatchEvent)
		close(ch)
		return ch, nil
	}
	sub := r.KubeConfigWatcher.Subscribe()
	out := make(chan *model.KubeConfigWatchEvent)
	go func() {
		defer close(out)
		defer sub.Close()
		first := true
		ch := sub.Chan()
		for {
			select {
			case <-ctx.Done():
				return
			case cfg, ok := <-ch:
				if !ok {
					return
				}
				if cfg == nil {
					continue
				}
				t := model.WatchEventTypeModified
				if first {
					t = model.WatchEventTypeAdded
					first = false
				}
				ev := &model.KubeConfigWatchEvent{
					Type:   t,
					Object: &model.KubeConfig{Config: cfg},
				}
				select {
				case out <- ev:
				case <-ctx.Done():
					return
				}
			}
		}
	}()
	return out, nil
}

// KubeConfig returns KubeConfigResolver implementation.
func (r *Resolver) KubeConfig() KubeConfigResolver { return &kubeConfigResolver{r} }

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

type kubeConfigResolver struct{ *Resolver }
type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
