package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"fmt"
	"time"
)

// UpdateSettings is the resolver for the updateSettings field.
// Write-through: push to the cloud, then publish to the shared Hub so
// active subscribers update immediately. Persistence is intentionally NOT
// done here — the engine is the sole syncstore writer; it persists this
// change when the cloud echoes it back on its stream (single-writer keeps
// the engine's version/mirror coherent). Read-after-write via the
// `settings` query may briefly lag, but the UI consumes `settingsWatch`,
// which the Hub publish satisfies at once.
func (r *mutationResolver) UpdateSettings(ctx context.Context, input UpdateSettingsInput) (*Settings, error) {
	ci := cloudInput(input)
	out, err := r.Cloud.UpdateSettings(ctx, bearer(ctx), ci)
	if err != nil {
		// Offline/transient: persist (coalesced) so the engine replays
		// it on its next Live. Still surface the error — the client
		// must know it hasn't reached the cloud yet.
		if qErr := r.Queue.Enqueue(ci); qErr != nil {
			return nil, fmt.Errorf("%w (also failed to queue: %v)", err, qErr)
		}
		return nil, err
	}
	r.Hub.Publish(out)
	return toGraphSettings(out), nil
}

// Ping is the resolver for the ping field.
func (r *queryResolver) Ping(ctx context.Context) (string, error) {
	return "pong", nil
}

// Settings is the resolver for the settings field. Served entirely from
// the engine-maintained syncstore — the engine owns the only cloud
// connection, so reads never touch the network. An empty store (engine
// never synced, e.g. logged out) yields the zero value, not an error.
func (r *queryResolver) Settings(ctx context.Context) (*Settings, error) {
	env, err := r.Store.Load()
	if err != nil {
		return nil, err
	}
	return toGraphSettings(env.Data), nil
}

// SyncStatus is the resolver for the syncStatus field.
func (r *queryResolver) SyncStatus(ctx context.Context) (*SyncStatus, error) {
	return toGraphSyncStatus(r.Sync.Status()), nil
}

// Tick is the resolver for the tick field. Streams 1, 2, 3, … on the
// configured interval. Cancellation comes from the gqlgen runtime when the
// client unsubscribes (or the WebSocket closes).
func (r *subscriptionResolver) Tick(ctx context.Context) (<-chan int, error) {
	ch := make(chan int, 1)
	go func() {
		defer close(ch)
		t := time.NewTicker(tickInterval())
		defer t.Stop()
		for n := 1; ; n++ {
			select {
			case <-ctx.Done():
				return
			case <-t.C:
			}
			select {
			case ch <- n:
			case <-ctx.Done():
				return
			}
		}
	}()
	return ch, nil
}

// SettingsWatch is the resolver for the settingsWatch field. Subscribes
// the shared Hub only — the engine is the single upstream consumer and
// fans cloud changes (plus mutation publishes) through this Hub. A new
// subscriber gets the current syncstore snapshot first so it doesn't have
// to wait for the next change, then live Hub deltas.
func (r *subscriptionResolver) SettingsWatch(ctx context.Context) (<-chan *Settings, error) {
	hubCh, unsub := r.Hub.Subscribe()
	return streamWithSnapshot(ctx, hubCh, unsub, toGraphSettings, func() (*Settings, bool) {
		// A failed load (e.g. nothing persisted yet) is non-fatal here:
		// ok=false skips the snapshot (see streamWithSnapshot's doc).
		env, err := r.Store.Load()
		if err != nil {
			return nil, false
		}
		return toGraphSettings(env.Data), true
	}), nil
}

// SyncStatusWatch is the resolver for the syncStatusWatch field. Emits
// the current status immediately (so a new subscriber doesn't wait for the
// next transition), then every subsequent transition from the engine.
func (r *subscriptionResolver) SyncStatusWatch(ctx context.Context) (<-chan *SyncStatus, error) {
	sub, unsub := r.Sync.WatchStatus()
	return streamWithSnapshot(ctx, sub, unsub, toGraphSyncStatus, func() (*SyncStatus, bool) {
		return toGraphSyncStatus(r.Sync.Status()), true
	}), nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
