package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"

	"github.com/kubetail-org/kstack-app/sidecar/internal/auth"
)

// AuthLoginStart is the resolver for the authLoginStart field: setup runs synchronously
// (its error surfaces here), the browser round-trip in the background, with the signed-in
// state arriving via authStateWatch.
func (r *mutationResolver) AuthLoginStart(ctx context.Context) (bool, error) {
	if err := r.Auth.StartLogin(ctx); err != nil {
		return false, err
	}
	return true, nil
}

// AuthLogout is the resolver for the authLogout field: clear locally, broadcast
// signed-out, revoke best-effort.
func (r *mutationResolver) AuthLogout(ctx context.Context) (bool, error) {
	if err := r.Auth.Logout(ctx); err != nil {
		return false, err
	}
	return true, nil
}

// AuthState is the resolver for the authState field. auth.State binds directly to the
// GraphQL type, so only schema fields are exposed — State.Tokens never reaches the wire.
func (r *queryResolver) AuthState(ctx context.Context) (*auth.State, error) {
	state, err := r.Auth.Current(ctx)
	if err != nil {
		return nil, err
	}
	return &state, nil
}

// AuthStateWatch is the resolver for the authStateWatch field; the stream is
// current-on-subscribe, so its first value IS the snapshot.
func (r *subscriptionResolver) AuthStateWatch(ctx context.Context) (<-chan *auth.State, error) {
	states, cancel := r.Auth.Subscribe()
	return mapStream(ctx, states, cancel, func(s auth.State) *auth.State { return &s }), nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
