package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"fmt"

	"github.com/kubetail-org/kstack-app/sidecar/graph/model"
)

// ChatStream is the resolver for the chatStream field.
func (r *subscriptionResolver) ChatStream(ctx context.Context, input model.ChatInput) (<-chan *model.ChatChunk, error) {
	panic(fmt.Errorf("not implemented: ChatStream - chatStream"))
}
