package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"time"

	"github.com/kubetail-org/kstack-app/sidecar/internal/cluster/domain"
)

// FirstSeen is the resolver for the firstSeen field — see nilIfZeroTime.
func (r *clusterDataEventResolver) FirstSeen(ctx context.Context, obj *domain.ClusterDataEvent) (*time.Time, error) {
	return nilIfZeroTime(obj.FirstSeen), nil
}

// LastSeen is the resolver for the lastSeen field — see nilIfZeroTime.
func (r *clusterDataEventResolver) LastSeen(ctx context.Context, obj *domain.ClusterDataEvent) (*time.Time, error) {
	return nilIfZeroTime(obj.LastSeen), nil
}

// CreationTimestamp is the resolver for the creationTimestamp field — see nilIfZeroTime.
func (r *clusterDataObjectResolver) CreationTimestamp(ctx context.Context, obj *domain.ClusterDataObject) (*time.Time, error) {
	return nilIfZeroTime(obj.CreationTimestamp), nil
}

// ClusterDataKinds is the resolver for the clusterDataKinds field — one
// ClusterCache's discovered kind catalog (parent cluster id + cache id).
func (r *queryResolver) ClusterDataKinds(ctx context.Context, id domain.ObjectID, cacheID domain.ObjectID) ([]*domain.ClusterDataKind, error) {
	kinds, err := r.ClusterSvc.Data().ListKinds(ctx, id, cacheID)
	if err != nil {
		return nil, err
	}
	return ptrSlice(kinds), nil
}

// ClusterDataKindsWatch is the resolver for the clusterDataKindsWatch field — one
// ClusterCache's kind catalog as a delta watch (the live counterpart of
// clusterDataKinds), so the dashboard nav's kinds + counts track the cluster in
// real time.
func (r *subscriptionResolver) ClusterDataKindsWatch(ctx context.Context, id domain.ObjectID, cacheID domain.ObjectID) (<-chan *domain.ClusterDataKindChange, error) {
	ch, err := r.ClusterSvc.Data().WatchKinds(ctx, id, cacheID)
	if err != nil {
		return nil, err
	}
	return ptrStream(ctx, ch), nil
}

// ClusterDataEventsWatch is the resolver for the clusterDataEventsWatch field — one
// ClusterCache's cached Kubernetes Events as a delta watch, backing the dashboard's
// events table.
func (r *subscriptionResolver) ClusterDataEventsWatch(ctx context.Context, id domain.ObjectID, cacheID domain.ObjectID) (<-chan *domain.ClusterDataEventChange, error) {
	ch, err := r.ClusterSvc.Data().WatchEvents(ctx, id, cacheID)
	if err != nil {
		return nil, err
	}
	return ptrStream(ctx, ch), nil
}

// ClusterDataObjectsWatch is the resolver for the clusterDataObjectsWatch field — one
// kind's cached objects as a delta watch, backing the dashboard's per-kind tables.
func (r *subscriptionResolver) ClusterDataObjectsWatch(ctx context.Context, id domain.ObjectID, cacheID domain.ObjectID, apiVersion string, resource string) (<-chan *domain.ClusterDataObjectChange, error) {
	ch, err := r.ClusterSvc.Data().WatchObjects(ctx, id, cacheID, apiVersion, resource)
	if err != nil {
		return nil, err
	}
	return ptrStream(ctx, ch), nil
}

// ClusterDataEvent returns ClusterDataEventResolver implementation.
func (r *Resolver) ClusterDataEvent() ClusterDataEventResolver { return &clusterDataEventResolver{r} }

// ClusterDataObject returns ClusterDataObjectResolver implementation.
func (r *Resolver) ClusterDataObject() ClusterDataObjectResolver {
	return &clusterDataObjectResolver{r}
}

type clusterDataEventResolver struct{ *Resolver }
type clusterDataObjectResolver struct{ *Resolver }
