package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"

	"github.com/kubetail-org/kstack-app/sidecar/internal/cluster/domain"
)

// Stats is the resolver for the cache.stats field — a resolver so a query pays the stat
// cost only when it selects them.
func (r *clusterCacheResolver) Stats(ctx context.Context, obj *domain.ClusterCache) (*domain.ClusterCacheStats, error) {
	return r.ClusterSvc.Caches().GetStats(ctx, obj.ClusterID, obj.ID)
}

// Stats is the resolver for the stats field — the discovery pass's gauges, sampled from
// the controller because status deliberately stores none. Null until a pass has run.
func (r *clusterCacheGVRDiscoveryResolver) Stats(ctx context.Context, obj *domain.ClusterCacheGVRDiscovery) (*domain.ClusterCacheGVRDiscoveryStats, error) {
	return r.ClusterSvc.Discovery().GetStats(ctx, obj.ID)
}

// Stats is the resolver for the stats field.
func (r *clusterCacheGVRSyncResolver) Stats(ctx context.Context, obj *domain.ClusterCacheGVRSync) (*domain.ClusterCacheGVRSyncStats, error) {
	return r.ClusterSvc.Syncs().GetStats(ctx, obj.ID)
}

// ClusterCacheClear is the resolver for the clusterCacheClear field: delete the on-disk
// cache and restart that cache's workers onto the emptied file — nothing else would
// rebuild them. The cluster record stays and re-syncs from scratch.
func (r *mutationResolver) ClusterCacheClear(ctx context.Context, id domain.ObjectID) (*domain.Cluster, error) {
	return r.ClusterSvc.Caches().Clear(ctx, id)
}

// ClusterCacheEvents is the resolver for the clusterCacheEvents field — a
// ClusterCache's event timeline.
func (r *queryResolver) ClusterCacheEvents(ctx context.Context, id domain.ObjectID, category *string, limit *int) ([]*domain.Event, error) {
	evs, err := r.ClusterSvc.Caches().ListEvents(ctx, id, category, limit)
	if err != nil {
		return nil, err
	}
	return ptrSlice(evs), nil
}

// ClusterCacheGVRSyncEvents is the resolver for the clusterCacheGVRSyncEvents field.
func (r *queryResolver) ClusterCacheGVRSyncEvents(ctx context.Context, id domain.ObjectID, category *string, limit *int) ([]*domain.Event, error) {
	evs, err := r.ClusterSvc.Syncs().ListEvents(ctx, id, category, limit)
	if err != nil {
		return nil, err
	}
	return ptrSlice(evs), nil
}

// ClusterCachesWatch is the resolver for the clusterCachesWatch field — cache
// records as a delta watch parallel to clustersWatch, joined to clusters
// client-side by clusterID.
func (r *subscriptionResolver) ClusterCachesWatch(ctx context.Context) (<-chan *domain.ClusterCacheChange, error) {
	ch, err := r.ClusterSvc.Caches().Watch(ctx)
	if err != nil {
		return nil, err
	}
	return ptrStream(ctx, ch), nil
}

// ClusterCacheSyncHealthWatch is the resolver for the clusterCacheSyncHealthWatch field.
func (r *subscriptionResolver) ClusterCacheSyncHealthWatch(ctx context.Context) (<-chan *domain.ClusterCacheSyncHealth, error) {
	ch, err := r.ClusterSvc.Caches().WatchSyncHealth(ctx)
	if err != nil {
		return nil, err
	}
	return ptrStream(ctx, ch), nil
}

// ClusterCacheGVRDiscoveriesWatch is the resolver for the
// clusterCacheGVRDiscoveriesWatch field — the caches' GVR-discovery records as a delta
// watch parallel to clusterCachesWatch, joined to caches client-side by cacheID.
func (r *subscriptionResolver) ClusterCacheGVRDiscoveriesWatch(ctx context.Context) (<-chan *domain.ClusterCacheGVRDiscoveryChange, error) {
	ch, err := r.ClusterSvc.Discovery().Watch(ctx)
	if err != nil {
		return nil, err
	}
	return ptrStream(ctx, ch), nil
}

// ClusterCacheGVRSyncsWatch is the resolver for the clusterCacheGVRSyncsWatch field —
// one cache's per-kind sync records as a delta watch. Cache-scoped, unlike the sibling
// object watches: there is one record per synced kind.
func (r *subscriptionResolver) ClusterCacheGVRSyncsWatch(ctx context.Context, cacheID domain.ObjectID) (<-chan *domain.ClusterCacheGVRSyncChange, error) {
	ch, err := r.ClusterSvc.Syncs().Watch(ctx, cacheID)
	if err != nil {
		return nil, err
	}
	return ptrStream(ctx, ch), nil
}

// ClusterCacheStatsWatch is the resolver for the clusterCacheStatsWatch field — one
// cache's contents as a live gauge, streamed because the ClusterCache.stats field freezes
// once its record stops changing.
func (r *subscriptionResolver) ClusterCacheStatsWatch(ctx context.Context, id domain.ObjectID, cacheID domain.ObjectID) (<-chan *domain.ClusterCacheStats, error) {
	ch, err := r.ClusterSvc.Caches().WatchStats(ctx, id, cacheID)
	if err != nil {
		return nil, err
	}
	return ptrStream(ctx, ch), nil
}

// ClusterCacheEventsWatch is the resolver for the clusterCacheEventsWatch field —
// the live event tail for one ClusterCache, decoupled from clusterCachesWatch.
func (r *subscriptionResolver) ClusterCacheEventsWatch(ctx context.Context, id domain.ObjectID, category *string) (<-chan *domain.Event, error) {
	ch, err := r.ClusterSvc.Caches().WatchEvents(ctx, id, category)
	if err != nil {
		return nil, err
	}
	return ptrStream(ctx, ch), nil
}

// ClusterCacheGVRSyncEventsWatch is the resolver for the clusterCacheGVRSyncEventsWatch field.
func (r *subscriptionResolver) ClusterCacheGVRSyncEventsWatch(ctx context.Context, id domain.ObjectID, category *string) (<-chan *domain.Event, error) {
	ch, err := r.ClusterSvc.Syncs().WatchEvents(ctx, id, category)
	if err != nil {
		return nil, err
	}
	return ptrStream(ctx, ch), nil
}

// ClusterCache returns ClusterCacheResolver implementation.
func (r *Resolver) ClusterCache() ClusterCacheResolver { return &clusterCacheResolver{r} }

// ClusterCacheGVRDiscovery returns ClusterCacheGVRDiscoveryResolver implementation.
func (r *Resolver) ClusterCacheGVRDiscovery() ClusterCacheGVRDiscoveryResolver {
	return &clusterCacheGVRDiscoveryResolver{r}
}

// ClusterCacheGVRSync returns ClusterCacheGVRSyncResolver implementation.
func (r *Resolver) ClusterCacheGVRSync() ClusterCacheGVRSyncResolver {
	return &clusterCacheGVRSyncResolver{r}
}

type clusterCacheResolver struct{ *Resolver }
type clusterCacheGVRDiscoveryResolver struct{ *Resolver }
type clusterCacheGVRSyncResolver struct{ *Resolver }
