package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"fmt"

	"github.com/kubetail-org/kstack-app/sidecar/graph/model"
	"github.com/kubetail-org/kstack-app/sidecar/internal/cluster/domain"
)

// Permissions is the resolver for the permissions field — the one live cluster
// call on the Cluster surface, so it runs only when explicitly selected.
// TODO: run a SelfSubjectRulesReview; errors until implemented.
func (r *clusterPrincipalResolver) Permissions(ctx context.Context, obj *domain.ClusterPrincipal, namespace string) (*model.ClusterPermissions, error) {
	return nil, fmt.Errorf("not implemented: permissions")
}

// ClusterEnabledSet is the resolver for the clusterEnabledSet field. The change
// reaches the webview through the cluster watch.
func (r *mutationResolver) ClusterEnabledSet(ctx context.Context, id domain.ObjectID, enabled bool) (*domain.Cluster, error) {
	return r.ClusterSvc.Clusters().SetEnabled(ctx, id, enabled)
}

// ClusterSyncEnabledSet is the resolver for the clusterSyncEnabledSet field.
func (r *mutationResolver) ClusterSyncEnabledSet(ctx context.Context, id domain.ObjectID, syncEnabled bool) (*domain.Cluster, error) {
	return r.ClusterSvc.Clusters().SetSyncEnabled(ctx, id, syncEnabled)
}

// ClusterConnectionRetry is the resolver for the clusterConnectionRetry field.
// The retry's outcome lands on the record's conditions and reaches the webview
// through the cluster watch, not here.
func (r *mutationResolver) ClusterConnectionRetry(ctx context.Context, id domain.ObjectID) (bool, error) {
	if err := r.ClusterSvc.RetryConnection(ctx, id); err != nil {
		return false, err
	}
	return true, nil
}

// ClusterDelete is the resolver for the clusterDelete field. Deleting the
// Cluster cascades (beehive GC) to its ClusterCache child.
func (r *mutationResolver) ClusterDelete(ctx context.Context, id domain.ObjectID) (bool, error) {
	if err := r.ClusterSvc.Clusters().Delete(ctx, id); err != nil {
		return false, err
	}
	return true, nil
}

// Cluster is the resolver for the cluster field. An untracked or
// deletion-pending id is null per the schema, not an error.
func (r *queryResolver) Cluster(ctx context.Context, id domain.ObjectID) (*domain.Cluster, error) {
	return r.ClusterSvc.Clusters().Get(ctx, id)
}

// Clusters is the resolver for the clusters field. Nested objects resolve lazily
// per-selection.
func (r *queryResolver) Clusters(ctx context.Context) ([]*domain.Cluster, error) {
	return r.ClusterSvc.Clusters().List(ctx)
}

// ClusterEvents is the resolver for the clusterEvents field — a cluster's event
// timeline.
func (r *queryResolver) ClusterEvents(ctx context.Context, id domain.ObjectID, category *string, limit *int) ([]*domain.Event, error) {
	evs, err := r.ClusterSvc.Clusters().ListEvents(ctx, id, category, limit)
	if err != nil {
		return nil, err
	}
	return ptrSlice(evs), nil
}

// ClustersWatch is the resolver for the clustersWatch field — the cluster list as
// a delta watch (Added snapshot, then per-cluster Added/Modified/Deleted). Cache
// sync status rides clusterCachesWatch, joined client-side.
func (r *subscriptionResolver) ClustersWatch(ctx context.Context) (<-chan *domain.ClusterChange, error) {
	ch, err := r.ClusterSvc.Clusters().Watch(ctx)
	if err != nil {
		return nil, err
	}
	return ptrStream(ctx, ch), nil
}

// ClusterEventsWatch is the resolver for the clusterEventsWatch field — the live
// event tail for one cluster, decoupled from clustersWatch.
func (r *subscriptionResolver) ClusterEventsWatch(ctx context.Context, id domain.ObjectID, category *string) (<-chan *domain.Event, error) {
	ch, err := r.ClusterSvc.Clusters().WatchEvents(ctx, id, category)
	if err != nil {
		return nil, err
	}
	return ptrStream(ctx, ch), nil
}

// ClusterScheduleWatch is the resolver for the clusterScheduleWatch field — the
// live reconcile-schedule gauge for one cluster (next-attempt countdown),
// decoupled from clustersWatch.
func (r *subscriptionResolver) ClusterScheduleWatch(ctx context.Context, id domain.ObjectID) (<-chan *domain.Schedule, error) {
	ch, err := r.ClusterSvc.Clusters().WatchSchedule(ctx, id)
	if err != nil {
		return nil, err
	}
	return ptrStream(ctx, ch), nil
}

// ClusterPrincipal returns ClusterPrincipalResolver implementation.
func (r *Resolver) ClusterPrincipal() ClusterPrincipalResolver { return &clusterPrincipalResolver{r} }

type clusterPrincipalResolver struct{ *Resolver }
