package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"errors"
	"fmt"

	"github.com/amorey/beehive"
	"github.com/kubetail-org/kstack-app/sidecar/graph/model"
	"github.com/kubetail-org/kstack-app/sidecar/internal/auth"
	"github.com/kubetail-org/kstack-app/sidecar/internal/controllers"
)

// Status is the resolver for the status field. It pairs the status block with
// the cluster's ID, which the cache child resolver needs to query its sub-API.
func (r *clusterResolver) Status(ctx context.Context, obj *controllers.Cluster) (*model.ClusterStatus, error) {
	return &model.ClusterStatus{ClusterStatus: obj.Status, ClusterID: obj.ID}, nil
}

// Permissions is the resolver for the permissions field — the one live cluster
// call on the Cluster surface, so it runs only when explicitly selected.
// TODO: run a SelfSubjectRulesReview. No honest placeholder for RBAC data,
// so this errors until implemented.
func (r *clusterPrincipalResolver) Permissions(ctx context.Context, obj *controllers.ClusterPrincipal, namespace string) (*model.ClusterPermissions, error) {
	return nil, fmt.Errorf("not implemented: permissions")
}

// Cache is the resolver for the cache field: live stats from the per-cluster
// cache (a resolver so a query only pays the stat query when it selects them).
func (r *clusterStatusResolver) Cache(ctx context.Context, obj *model.ClusterStatus) (*controllers.CacheStats, error) {
	return r.buildCacheStats(ctx, obj.ClusterID)
}

// ClusterSyncEnabledSet is the resolver for the clusterSyncEnabledSet field.
func (r *mutationResolver) ClusterSyncEnabledSet(ctx context.Context, id string, syncEnabled bool) (*controllers.Cluster, error) {
	obj, err := r.clusterByID(ctx, id)
	if err != nil {
		return nil, err
	}
	spec := obj.Spec
	spec.IsSyncEnabled = syncEnabled
	updated, err := r.ClusterClient.Update(ctx, obj.ID, spec)
	if err != nil {
		return nil, err
	}
	cluster := r.buildCluster(ctx, updated)
	return &cluster, nil
}

// ClusterConnectionRetry is the resolver for the clusterConnectionRetry field.
// The retry's outcome is not returned here — it lands on the record's
// conditions and reaches the webview through the cluster watch.
func (r *mutationResolver) ClusterConnectionRetry(ctx context.Context, id string) (bool, error) {
	obj, err := r.clusterByID(ctx, id)
	if err != nil {
		return false, err
	}
	spec := obj.Spec
	spec.RetryGeneration++
	_, err = r.ClusterClient.Update(ctx, obj.ID, spec)
	if err != nil {
		return false, err
	}
	return true, nil
}

// ClusterCacheClear is the resolver for the clusterCacheClear field: delete
// the on-disk cache and bounce the sync engine; the cluster record (returned)
// stays. A still-eligible cluster re-syncs from scratch.
func (r *mutationResolver) ClusterCacheClear(ctx context.Context, id string) (*controllers.Cluster, error) {
	// Validate cluster exists before touching disk.
	obj, err := r.clusterByID(ctx, id)
	if err != nil {
		return nil, err
	}

	// Delete the on-disk cache files.
	if err := r.CacheManager.DeleteCacheFiles(ctx, string(controllers.ClusterID(id))); err != nil {
		return nil, err
	}

	// Bump PokeSyncGeneration on the parent Cluster to bounce the running engine.
	spec := obj.Spec
	spec.PokeSyncGeneration++
	updated, err := r.ClusterClient.Update(ctx, obj.ID, spec)
	if err != nil {
		return nil, err
	}
	cluster := r.buildCluster(ctx, updated)
	return &cluster, nil
}

// ClusterDelete is the resolver for the clusterDelete field. Deletes the
// parent ClusterSource so beehive GC cascades to Cluster → ClusterCache.
func (r *mutationResolver) ClusterDelete(ctx context.Context, id string) (bool, error) {
	obj, err := r.clusterByID(ctx, id)
	if err != nil {
		return false, err
	}

	// Find and delete the parent ClusterSource; GC cascades to Cluster + ClusterCache.
	if obj.Spec.Source.Kubeconfig != nil {
		srcObj, srcErr := r.SrcClient.GetBySlug(ctx, controllers.ClusterSourceSlug(obj.Spec.Source.Kubeconfig.Context))
		if srcErr == nil {
			if err := r.SrcClient.Delete(ctx, srcObj.ID); err != nil {
				return false, err
			}
			return true, nil
		}
	}

	// Fallback: delete the Cluster directly (no parent source or lookup failed).
	if err := r.ClusterClient.Delete(ctx, obj.ID); err != nil {
		return false, err
	}
	return true, nil
}

// AuthLoginStart is the resolver for the authLoginStart field. It runs the
// flow's setup phase (loopback bind + browser open) synchronously and returns
// any setup error — surfaced here as a GraphQL error — then finishes the browser
// round-trip in the background; the resulting signed-in state is delivered via
// authStateWatch.
func (r *mutationResolver) AuthLoginStart(ctx context.Context) (bool, error) {
	if err := r.Auth.StartLogin(ctx); err != nil {
		return false, err
	}
	return true, nil
}

// AuthLogout is the resolver for the authLogout field. Delegates to the auth
// service, which clears the local credentials, broadcasts signed-out, and
// revokes the token server-side (best-effort).
func (r *mutationResolver) AuthLogout(ctx context.Context) (bool, error) {
	if err := r.Auth.Logout(ctx); err != nil {
		return false, err
	}
	return true, nil
}

// Cluster is the resolver for the cluster field. An untracked or
// deletion-pending id is null per the schema, not an error.
func (r *queryResolver) Cluster(ctx context.Context, id string) (*controllers.Cluster, error) {
	obj, err := r.ClusterClient.GetBySlug(ctx, controllers.ClusterSlug(controllers.ClusterID(id)))
	if errors.Is(err, beehive.ErrNotFound) {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	if obj.DeletionRequestedAt != nil {
		return nil, nil
	}
	cluster := r.buildCluster(ctx, obj)
	return &cluster, nil
}

// Clusters is the resolver for the clusters field. Reads all Cluster records;
// ephemeral nested objects resolve lazily per-selection.
func (r *queryResolver) Clusters(ctx context.Context) ([]*controllers.Cluster, error) {
	objs, err := r.ClusterClient.List(ctx)
	if err != nil {
		return nil, err
	}
	clusters := make([]*controllers.Cluster, 0, len(objs))
	for _, obj := range objs {
		if obj.DeletionRequestedAt != nil {
			continue
		}
		c := r.buildCluster(ctx, obj)
		clusters = append(clusters, &c)
	}
	return clusters, nil
}

// AuthState is the resolver for the authState field. auth.State is bound
// directly to the GraphQL AuthState type (see gqlgen.yml) — only the schema
// fields are exposed, so State.Tokens never reaches the wire.
func (r *queryResolver) AuthState(ctx context.Context) (*auth.State, error) {
	state, err := r.Auth.Current(ctx)
	if err != nil {
		return nil, err
	}
	return &state, nil
}

// ClustersWatch is the resolver for the clustersWatch field. Emits the current
// cluster list on subscribe, then re-emits on every Cluster or ClusterCache
// change (so sync-status updates propagate to the webview).
func (r *subscriptionResolver) ClustersWatch(ctx context.Context) (<-chan []*controllers.Cluster, error) {
	// Seed with the current list.
	objs, err := r.ClusterClient.List(ctx)
	if err != nil {
		return nil, err
	}
	seed := make([]*controllers.Cluster, 0, len(objs))
	for _, obj := range objs {
		if obj.DeletionRequestedAt != nil {
			continue
		}
		c := r.buildCluster(ctx, obj)
		seed = append(seed, &c)
	}

	clusterCh, err := r.ClusterClient.WatchList(ctx)
	if err != nil {
		return nil, err
	}
	cacheCh, err := r.CacheClient.WatchList(ctx)
	if err != nil {
		return nil, err
	}

	out := make(chan []*controllers.Cluster, 1)
	out <- seed

	go func() {
		defer close(out)

		emit := func() {
			list, err := r.ClusterClient.List(ctx)
			if err != nil {
				return
			}
			clusters := make([]*controllers.Cluster, 0, len(list))
			for _, obj := range list {
				if obj.DeletionRequestedAt != nil {
					continue
				}
				c := r.buildCluster(ctx, obj)
				clusters = append(clusters, &c)
			}
			select {
			case out <- clusters:
			case <-ctx.Done():
			}
		}

		for {
			select {
			case <-ctx.Done():
				return
			case _, ok := <-clusterCh:
				if !ok {
					return
				}
				emit()
			case _, ok := <-cacheCh:
				if !ok {
					return
				}
				emit()
			}
		}
	}()
	return out, nil
}

// ChatStream is the resolver for the chatStream field.
func (r *subscriptionResolver) ChatStream(ctx context.Context, input model.ChatInput) (<-chan *model.ChatChunk, error) {
	panic(fmt.Errorf("not implemented: ChatStream - chatStream"))
}

// AuthStateWatch is the resolver for the authStateWatch field. Emits the current
// auth-state snapshot, then a fresh snapshot on every sign-in / sign-out / refresh
// change. The auth-state stream is latest-value (current-on-subscribe), so its
// first value already seeds the current state — just map each State through.
func (r *subscriptionResolver) AuthStateWatch(ctx context.Context) (<-chan *auth.State, error) {
	states, cancel := r.Auth.Subscribe()
	return mapStream(ctx, states, cancel, func(s auth.State) *auth.State { return &s }), nil
}

// Cluster returns ClusterResolver implementation.
func (r *Resolver) Cluster() ClusterResolver { return &clusterResolver{r} }

// ClusterPrincipal returns ClusterPrincipalResolver implementation.
func (r *Resolver) ClusterPrincipal() ClusterPrincipalResolver { return &clusterPrincipalResolver{r} }

// ClusterStatus returns ClusterStatusResolver implementation.
func (r *Resolver) ClusterStatus() ClusterStatusResolver { return &clusterStatusResolver{r} }

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

type clusterResolver struct{ *Resolver }
type clusterPrincipalResolver struct{ *Resolver }
type clusterStatusResolver struct{ *Resolver }
type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//  - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//    it when you're done.
//  - You have helper methods in this file. Move them out to keep these resolver files clean.
/*
	func (r *clusterStatusResolver) Source(ctx context.Context, obj *model.ClusterStatus) (*controllers.ClusterSourceStatus, error) {
	return &obj.ClusterStatus.Source, nil
}
func (r *clusterStatusResolver) Server(ctx context.Context, obj *model.ClusterStatus) (*controllers.ClusterServer, error) {
	return &obj.ClusterStatus.Server, nil
}
func (r *clusterStatusResolver) Principal(ctx context.Context, obj *model.ClusterStatus) (*controllers.ClusterPrincipal, error) {
	return &obj.ClusterStatus.Principal, nil
}
func (r *clusterStatusResolver) Conditions(ctx context.Context, obj *model.ClusterStatus) ([]*controllers.ClusterCondition, error) {
	return ptrSlice(obj.ClusterStatus.Conditions), nil
}
func (r *clusterStatusResolver) SyncStatus(ctx context.Context, obj *model.ClusterStatus) (*controllers.ClusterCacheStatus, error) {
	return &obj.ClusterStatus.SyncStatus, nil
}
*/
