package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"fmt"
	"time"

	"github.com/kubetail-org/kstack-app/sidecar/graph/model"
	"github.com/kubetail-org/kstack-app/sidecar/internal/auth"
	"github.com/kubetail-org/kstack-app/sidecar/internal/clustersvc"
)

// Caches is the resolver for the caches field — the caches this cluster owns. A
// separate beehive read, so it runs only when selected.
func (r *clusterResolver) Caches(ctx context.Context, obj *clustersvc.Cluster) ([]*clustersvc.ClusterCache, error) {
	return r.ClusterSvc.Caches().ListByCluster(ctx, obj.ID)
}

// Events is the resolver for the events field — this cluster's event timeline. A
// separate beehive read, so it runs only when selected.
func (r *clusterResolver) Events(ctx context.Context, obj *clustersvc.Cluster, category *string, limit *int) ([]*clustersvc.Event, error) {
	evs, err := r.ClusterSvc.ListEvents(ctx, obj.ID, category, limit)
	if err != nil {
		return nil, err
	}
	return ptrSlice(evs), nil
}

// Kinds is the resolver for the kinds field — this cache's discovered kind catalog.
// Both ids come off the record, so they cannot name different caches.
func (r *clusterCacheResolver) Kinds(ctx context.Context, obj *clustersvc.ClusterCache) ([]*clustersvc.ClusterCachedDataKind, error) {
	kinds, err := r.ClusterSvc.CachedData().ListKinds(ctx, obj.Owner.ID, obj.ID)
	if err != nil {
		return nil, err
	}
	return ptrSlice(kinds), nil
}

// CachedKinds is the resolver for the cachedKinds field — the kinds this cache
// mirrors. Keyed by the cache; the catalog between them is resolved in the service.
func (r *clusterCacheResolver) CachedKinds(ctx context.Context, obj *clustersvc.ClusterCache) ([]*clustersvc.ClusterCachedKind, error) {
	return r.ClusterSvc.CachedKinds().ListByCache(ctx, obj.ID)
}

// Events is the resolver for the events field — this cache's own event timeline.
// A separate beehive read, so it runs only when selected.
func (r *clusterCacheResolver) Events(ctx context.Context, obj *clustersvc.ClusterCache, category *string, limit *int) ([]*clustersvc.Event, error) {
	evs, err := r.ClusterSvc.ListEvents(ctx, obj.ID, category, limit)
	if err != nil {
		return nil, err
	}
	return ptrSlice(evs), nil
}

// FirstSeen is the resolver for the firstSeen field — see nilIfZeroTime.
func (r *clusterCachedDataEventResolver) FirstSeen(ctx context.Context, obj *clustersvc.ClusterCachedDataEvent) (*time.Time, error) {
	return nilIfZeroTime(obj.FirstSeen), nil
}

// LastSeen is the resolver for the lastSeen field — see nilIfZeroTime.
func (r *clusterCachedDataEventResolver) LastSeen(ctx context.Context, obj *clustersvc.ClusterCachedDataEvent) (*time.Time, error) {
	return nilIfZeroTime(obj.LastSeen), nil
}

// CreationTimestamp is the resolver for the creationTimestamp field — see nilIfZeroTime.
func (r *clusterCachedDataObjectResolver) CreationTimestamp(ctx context.Context, obj *clustersvc.ClusterCachedDataObject) (*time.Time, error) {
	return nilIfZeroTime(obj.CreationTimestamp), nil
}

// Events is the resolver for the events field — this kind's sync-transition
// history. A separate beehive read, so it runs only when selected.
func (r *clusterCachedKindResolver) Events(ctx context.Context, obj *clustersvc.ClusterCachedKind, category *string, limit *int) ([]*clustersvc.Event, error) {
	evs, err := r.ClusterSvc.ListEvents(ctx, obj.ID, category, limit)
	if err != nil {
		return nil, err
	}
	return ptrSlice(evs), nil
}

// SyncEnabled is the resolver for the syncEnabled field: the wire's positive form over the
// stored Paused. The storage field is inverted so a record written before it decodes as
// syncing rather than stopping the fleet on the upgrade; this is the one negation.
func (r *clusterCachedKindSpecResolver) SyncEnabled(_ context.Context, obj *clustersvc.ClusterCachedKindSpec) (bool, error) {
	return !obj.Paused, nil
}

// Permissions is the resolver for the permissions field — the one live cluster
// call on the Cluster surface, so it runs only when explicitly selected.
// TODO: run a SelfSubjectRulesReview; errors until implemented.
func (r *clusterPrincipalResolver) Permissions(ctx context.Context, obj *clustersvc.ClusterPrincipal, namespace string) (*model.ClusterPermissions, error) {
	return nil, fmt.Errorf("not implemented: permissions")
}

// ClusterEnabledSet is the resolver for the clusterEnabledSet field. The change
// reaches the webview through the cluster watch.
func (r *mutationResolver) ClusterEnabledSet(ctx context.Context, id clustersvc.ObjectID, enabled bool) (*clustersvc.Cluster, error) {
	return r.ClusterSvc.Clusters().SetEnabled(ctx, id, enabled)
}

// ClusterSyncEnabledSet is the resolver for the clusterSyncEnabledSet field.
func (r *mutationResolver) ClusterSyncEnabledSet(ctx context.Context, id clustersvc.ObjectID, syncEnabled bool) (*clustersvc.Cluster, error) {
	return r.ClusterSvc.Clusters().SetSyncEnabled(ctx, id, syncEnabled)
}

// ClusterConnectionRetry is the resolver for the clusterConnectionRetry field.
// The retry's outcome lands on the record's conditions and reaches the webview
// through the cluster watch, not here.
func (r *mutationResolver) ClusterConnectionRetry(ctx context.Context, id clustersvc.ObjectID) (bool, error) {
	if err := r.ClusterSvc.RetryConnection(ctx, id); err != nil {
		return false, err
	}
	return true, nil
}

// ClusterDelete is the resolver for the clusterDelete field. Deleting the
// Cluster cascades (beehive GC) to its ClusterCache child.
func (r *mutationResolver) ClusterDelete(ctx context.Context, id clustersvc.ObjectID) (bool, error) {
	if err := r.ClusterSvc.Clusters().Delete(ctx, id); err != nil {
		return false, err
	}
	return true, nil
}

// ClusterCacheClear is the resolver for the clusterCacheClear field: delete one cache's
// on-disk file and restart its workers onto the emptied one — nothing else would rebuild
// them. The record stays and re-syncs from scratch. The id is the cache's own.
func (r *mutationResolver) ClusterCacheClear(ctx context.Context, id clustersvc.ObjectID) (*clustersvc.ClusterCache, error) {
	return r.ClusterSvc.Caches().Clear(ctx, id)
}

// ClusterCachedKindSyncEnabledSet is the resolver for the clusterCachedKindSyncEnabledSet
// field: stop or resume one kind, keeping its cached rows either way. The id is the
// per-kind record's own.
func (r *mutationResolver) ClusterCachedKindSyncEnabledSet(ctx context.Context, id clustersvc.ObjectID, syncEnabled bool) (*clustersvc.ClusterCachedKind, error) {
	return r.ClusterSvc.CachedKinds().SetSyncEnabled(ctx, id, syncEnabled)
}

// AuthLoginStart is the resolver for the authLoginStart field: setup runs synchronously
// (its error surfaces here), the browser round-trip in the background, with the signed-in
// state arriving via authStateWatch.
func (r *mutationResolver) AuthLoginStart(ctx context.Context) (bool, error) {
	if err := r.Auth.StartLogin(ctx); err != nil {
		return false, err
	}
	return true, nil
}

// AuthLogout is the resolver for the authLogout field: clear locally, broadcast
// signed-out, revoke best-effort.
func (r *mutationResolver) AuthLogout(ctx context.Context) (bool, error) {
	if err := r.Auth.Logout(ctx); err != nil {
		return false, err
	}
	return true, nil
}

// Cluster is the resolver for the cluster field. An id naming nothing is null per the
// schema, not an error; one still being torn down resolves like any other, carrying
// its deletionRequestedAt.
func (r *queryResolver) Cluster(ctx context.Context, id clustersvc.ObjectID) (*clustersvc.Cluster, error) {
	return r.ClusterSvc.Clusters().Get(ctx, id)
}

// Clusters is the resolver for the clusters field. Nested objects resolve lazily
// per-selection.
func (r *queryResolver) Clusters(ctx context.Context) ([]*clustersvc.Cluster, error) {
	return r.ClusterSvc.Clusters().List(ctx)
}

// ClusterCache is the resolver for the clusterCache field. An id naming nothing is
// null per the schema, not an error.
func (r *queryResolver) ClusterCache(ctx context.Context, id clustersvc.ObjectID) (*clustersvc.ClusterCache, error) {
	return r.ClusterSvc.Caches().Get(ctx, id)
}

// ClusterCaches is the resolver for the clusterCaches field — every cache, or one
// cluster's when scoped. A nil clusterID is the unscoped read, not a missing argument.
func (r *queryResolver) ClusterCaches(ctx context.Context, clusterID *clustersvc.ObjectID) ([]*clustersvc.ClusterCache, error) {
	if clusterID != nil {
		return r.ClusterSvc.Caches().ListByCluster(ctx, *clusterID)
	}
	return r.ClusterSvc.Caches().List(ctx)
}

// ClusterCachedKind is the resolver for the clusterCachedKind field. An id
// naming nothing is null per the schema, not an error.
func (r *queryResolver) ClusterCachedKind(ctx context.Context, id clustersvc.ObjectID) (*clustersvc.ClusterCachedKind, error) {
	return r.ClusterSvc.CachedKinds().Get(ctx, id)
}

// ClusterCachedKinds is the resolver for the clusterCachedKinds field — every
// per-kind record, or one cache's when scoped.
func (r *queryResolver) ClusterCachedKinds(ctx context.Context, cacheID *clustersvc.ObjectID) ([]*clustersvc.ClusterCachedKind, error) {
	if cacheID != nil {
		return r.ClusterSvc.CachedKinds().ListByCache(ctx, *cacheID)
	}
	return r.ClusterSvc.CachedKinds().List(ctx)
}

// AuthState is the resolver for the authState field. auth.State binds directly to the
// GraphQL type, so only schema fields are exposed — State.Tokens never reaches the wire.
func (r *queryResolver) AuthState(ctx context.Context) (*auth.State, error) {
	state, err := r.Auth.Current(ctx)
	if err != nil {
		return nil, err
	}
	return &state, nil
}

// EventsWatch is the resolver for the eventsWatch field — the live event tail for any
// record with a timeline, decoupled from that record's own watch.
func (r *subscriptionResolver) EventsWatch(ctx context.Context, id clustersvc.ObjectID, category *string) (<-chan *clustersvc.EventWatchFrame, error) {
	st, err := r.ClusterSvc.WatchEvents(ctx, id, category)
	if err != nil {
		return nil, err
	}
	return watchStream(ctx, st), nil
}

// ClustersWatch is the resolver for the clustersWatch field — the cluster list as
// a delta watch (Added snapshot, then per-cluster Added/Modified/Deleted). Cache
// sync status rides clusterCachesWatch, joined client-side.
func (r *subscriptionResolver) ClustersWatch(ctx context.Context) (<-chan *clustersvc.ClusterWatchFrame, error) {
	st, err := r.ClusterSvc.Clusters().WatchList(ctx)
	if err != nil {
		return nil, err
	}
	return watchStream(ctx, st), nil
}

// ClusterScheduleWatch is the resolver for the clusterScheduleWatch field — the
// live reconcile-schedule gauge for one cluster (next-attempt countdown),
// decoupled from clustersWatch.
func (r *subscriptionResolver) ClusterScheduleWatch(ctx context.Context, id clustersvc.ObjectID) (<-chan *clustersvc.Schedule, error) {
	ch, err := r.ClusterSvc.Clusters().WatchSchedule(ctx, id)
	if err != nil {
		return nil, err
	}
	return ptrStream(ctx, ch), nil
}

// ClusterCachesWatch is the resolver for the clusterCachesWatch field — cache
// records as a delta watch parallel to clustersWatch, joined to clusters
// client-side by owner.id.
func (r *subscriptionResolver) ClusterCachesWatch(ctx context.Context) (<-chan *clustersvc.ClusterCacheWatchFrame, error) {
	st, err := r.ClusterSvc.Caches().WatchList(ctx)
	if err != nil {
		return nil, err
	}
	return watchStream(ctx, st), nil
}

// ClusterCacheHealthWatch is the resolver for the clusterCacheHealthWatch field.
func (r *subscriptionResolver) ClusterCacheHealthWatch(ctx context.Context) (<-chan *clustersvc.ClusterCacheHealth, error) {
	st, err := r.ClusterSvc.Caches().WatchHealth(ctx)
	if err != nil {
		return nil, err
	}
	return watchStream(ctx, st), nil
}

// ClusterCachedKindsWatch is the resolver for the clusterCachedKindsWatch field —
// one cache's per-kind sync records as a delta watch. Cache-scoped, unlike the sibling
// object watches: there is one record per synced kind.
func (r *subscriptionResolver) ClusterCachedKindsWatch(ctx context.Context, cacheID clustersvc.ObjectID) (<-chan *clustersvc.ClusterCachedKindWatchFrame, error) {
	st, err := r.ClusterSvc.CachedKinds().WatchByCache(ctx, cacheID)
	if err != nil {
		return nil, err
	}
	return watchStream(ctx, st), nil
}

// ClusterCacheStatsWatch is the resolver for the clusterCacheStatsWatch field — one
// cache's contents as a live gauge, streamed because the ClusterCache.stats field freezes
// once its record stops changing.
func (r *subscriptionResolver) ClusterCacheStatsWatch(ctx context.Context, id clustersvc.ObjectID, cacheID clustersvc.ObjectID) (<-chan *clustersvc.ClusterCacheStats, error) {
	stream, err := r.ClusterSvc.Caches().WatchStats(ctx, id, cacheID)
	if err != nil {
		return nil, err
	}
	return watchStream(ctx, stream), nil
}

// ClusterCacheSyncStatusWatch is the resolver for the clusterCacheSyncStatusWatch field —
// one cache's sync detail as a gauge. The only thing on the wire carrying a per-kind verdict.
func (r *subscriptionResolver) ClusterCacheSyncStatusWatch(ctx context.Context, id clustersvc.ObjectID, cacheID clustersvc.ObjectID) (<-chan *clustersvc.ClusterCacheSyncStatus, error) {
	stream, err := r.ClusterSvc.Caches().WatchSyncStatus(ctx, id, cacheID)
	if err != nil {
		return nil, err
	}
	return watchStream(ctx, stream), nil
}

// ClusterCachedDataKindsWatch is the resolver for the clusterCachedDataKindsWatch field — one
// ClusterCache's kind catalog as a delta watch (the live counterpart of
// clusterCachedDataKinds), so the dashboard nav's kinds + counts track the cluster in
// real time.
func (r *subscriptionResolver) ClusterCachedDataKindsWatch(ctx context.Context, id clustersvc.ObjectID, cacheID clustersvc.ObjectID) (<-chan *clustersvc.ClusterCachedDataKindWatchFrame, error) {
	stream, err := r.ClusterSvc.CachedData().WatchKinds(ctx, id, cacheID)
	if err != nil {
		return nil, err
	}
	return watchStream(ctx, stream), nil
}

// ClusterCachedDataEventsWatch is the resolver for the clusterCachedDataEventsWatch field — one
// ClusterCache's cached Kubernetes Events as a delta watch, backing the dashboard's
// events table.
func (r *subscriptionResolver) ClusterCachedDataEventsWatch(ctx context.Context, id clustersvc.ObjectID, cacheID clustersvc.ObjectID) (<-chan *clustersvc.ClusterCachedDataEventWatchFrame, error) {
	stream, err := r.ClusterSvc.CachedData().WatchEvents(ctx, id, cacheID)
	if err != nil {
		return nil, err
	}
	return watchStream(ctx, stream), nil
}

// ClusterCachedDataObjectsWatch is the resolver for the clusterCachedDataObjectsWatch field — one
// kind's cached objects as a delta watch, backing the dashboard's per-kind tables.
func (r *subscriptionResolver) ClusterCachedDataObjectsWatch(ctx context.Context, id clustersvc.ObjectID, cacheID clustersvc.ObjectID, apiVersion string, resource string) (<-chan *clustersvc.ClusterCachedDataObjectWatchFrame, error) {
	stream, err := r.ClusterSvc.CachedData().WatchObjects(ctx, id, cacheID, apiVersion, resource)
	if err != nil {
		return nil, err
	}
	return watchStream(ctx, stream), nil
}

// ChatStream is the resolver for the chatStream field.
func (r *subscriptionResolver) ChatStream(ctx context.Context, input model.ChatInput) (<-chan *model.ChatChunk, error) {
	panic(fmt.Errorf("not implemented: ChatStream - chatStream"))
}

// AuthStateWatch is the resolver for the authStateWatch field; the stream is
// current-on-subscribe, so its first value IS the snapshot.
func (r *subscriptionResolver) AuthStateWatch(ctx context.Context) (<-chan *auth.State, error) {
	states, cancel := r.Auth.Subscribe()
	return mapStream(ctx, states, cancel, func(s auth.State) *auth.State { return &s }), nil
}

// Cluster returns ClusterResolver implementation.
func (r *Resolver) Cluster() ClusterResolver { return &clusterResolver{r} }

// ClusterCache returns ClusterCacheResolver implementation.
func (r *Resolver) ClusterCache() ClusterCacheResolver { return &clusterCacheResolver{r} }

// ClusterCachedDataEvent returns ClusterCachedDataEventResolver implementation.
func (r *Resolver) ClusterCachedDataEvent() ClusterCachedDataEventResolver {
	return &clusterCachedDataEventResolver{r}
}

// ClusterCachedDataObject returns ClusterCachedDataObjectResolver implementation.
func (r *Resolver) ClusterCachedDataObject() ClusterCachedDataObjectResolver {
	return &clusterCachedDataObjectResolver{r}
}

// ClusterCachedKind returns ClusterCachedKindResolver implementation.
func (r *Resolver) ClusterCachedKind() ClusterCachedKindResolver {
	return &clusterCachedKindResolver{r}
}

// ClusterCachedKindSpec returns ClusterCachedKindSpecResolver implementation.
func (r *Resolver) ClusterCachedKindSpec() ClusterCachedKindSpecResolver {
	return &clusterCachedKindSpecResolver{r}
}

// ClusterPrincipal returns ClusterPrincipalResolver implementation.
func (r *Resolver) ClusterPrincipal() ClusterPrincipalResolver { return &clusterPrincipalResolver{r} }

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

type clusterResolver struct{ *Resolver }
type clusterCacheResolver struct{ *Resolver }
type clusterCachedDataEventResolver struct{ *Resolver }
type clusterCachedDataObjectResolver struct{ *Resolver }
type clusterCachedKindResolver struct{ *Resolver }
type clusterCachedKindSpecResolver struct{ *Resolver }
type clusterPrincipalResolver struct{ *Resolver }
type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
