package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"fmt"

	"github.com/kubetail-org/kstack-app/sidecar/graph/model"
	"github.com/kubetail-org/kstack-app/sidecar/internal/auth"
	"github.com/kubetail-org/kstack-app/sidecar/internal/cluster"
)

// Stats is the resolver for the cache.stats field: live stats from this specific
// cache (a resolver so a query only pays the stat query when it selects them). The
// ClusterCache child carries both its parent cluster id (the cache directory) and
// its own id (the cache file) for the lookup.
func (r *clusterCacheResolver) Stats(ctx context.Context, obj *cluster.ClusterCache) (*cluster.ClusterCacheStats, error) {
	return r.ClusterSvc.CacheStats(ctx, obj.ClusterID, obj.ID)
}

// Permissions is the resolver for the permissions field — the one live cluster
// call on the Cluster surface, so it runs only when explicitly selected.
// TODO: run a SelfSubjectRulesReview. No honest placeholder for RBAC data,
// so this errors until implemented.
func (r *clusterPrincipalResolver) Permissions(ctx context.Context, obj *cluster.ClusterPrincipal, namespace string) (*model.ClusterPermissions, error) {
	return nil, fmt.Errorf("not implemented: permissions")
}

// ClusterEnabledSet is the resolver for the clusterEnabledSet field. Enables or
// disables a cluster in the app; the change reaches the webview through the
// cluster watch.
func (r *mutationResolver) ClusterEnabledSet(ctx context.Context, id cluster.ObjectID, enabled bool) (*cluster.Cluster, error) {
	return r.ClusterSvc.SetEnabled(ctx, id, enabled)
}

// ClusterSyncEnabledSet is the resolver for the clusterSyncEnabledSet field.
func (r *mutationResolver) ClusterSyncEnabledSet(ctx context.Context, id cluster.ObjectID, syncEnabled bool) (*cluster.Cluster, error) {
	return r.ClusterSvc.SetSyncEnabled(ctx, id, syncEnabled)
}

// ClusterConnectionRetry is the resolver for the clusterConnectionRetry field.
// The retry's outcome is not returned here — it lands on the record's
// conditions and reaches the webview through the cluster watch.
func (r *mutationResolver) ClusterConnectionRetry(ctx context.Context, id cluster.ObjectID) (bool, error) {
	if err := r.ClusterSvc.RetryConnection(ctx, id); err != nil {
		return false, err
	}
	return true, nil
}

// ClusterCacheClear is the resolver for the clusterCacheClear field: delete
// the on-disk cache and bounce the sync engine; the cluster record (returned)
// stays. A still-eligible cluster re-syncs from scratch.
func (r *mutationResolver) ClusterCacheClear(ctx context.Context, id cluster.ObjectID) (*cluster.Cluster, error) {
	return r.ClusterSvc.ClearCache(ctx, id)
}

// ClusterDelete is the resolver for the clusterDelete field. Deletes the
// Cluster so beehive GC cascades to its ClusterCache child.
func (r *mutationResolver) ClusterDelete(ctx context.Context, id cluster.ObjectID) (bool, error) {
	if err := r.ClusterSvc.Delete(ctx, id); err != nil {
		return false, err
	}
	return true, nil
}

// AuthLoginStart is the resolver for the authLoginStart field. It runs the
// flow's setup phase (loopback bind + browser open) synchronously and returns
// any setup error — surfaced here as a GraphQL error — then finishes the browser
// round-trip in the background; the resulting signed-in state is delivered via
// authStateWatch.
func (r *mutationResolver) AuthLoginStart(ctx context.Context) (bool, error) {
	if err := r.Auth.StartLogin(ctx); err != nil {
		return false, err
	}
	return true, nil
}

// AuthLogout is the resolver for the authLogout field. Delegates to the auth
// service, which clears the local credentials, broadcasts signed-out, and
// revokes the token server-side (best-effort).
func (r *mutationResolver) AuthLogout(ctx context.Context) (bool, error) {
	if err := r.Auth.Logout(ctx); err != nil {
		return false, err
	}
	return true, nil
}

// Cluster is the resolver for the cluster field. An untracked or
// deletion-pending id is null per the schema, not an error.
func (r *queryResolver) Cluster(ctx context.Context, id cluster.ObjectID) (*cluster.Cluster, error) {
	return r.ClusterSvc.Get(ctx, id)
}

// Clusters is the resolver for the clusters field. Reads all Cluster records;
// ephemeral nested objects resolve lazily per-selection.
func (r *queryResolver) Clusters(ctx context.Context) ([]*cluster.Cluster, error) {
	return r.ClusterSvc.List(ctx)
}

// AuthState is the resolver for the authState field. auth.State is bound
// directly to the GraphQL AuthState type (see gqlgen.yml) — only the schema
// fields are exposed, so State.Tokens never reaches the wire.
func (r *queryResolver) AuthState(ctx context.Context) (*auth.State, error) {
	state, err := r.Auth.Current(ctx)
	if err != nil {
		return nil, err
	}
	return &state, nil
}

// ClustersWatch is the resolver for the clustersWatch field. Emits the current
// cluster list on subscribe, then re-emits on every Cluster or ClusterCache
// change (so sync-status updates propagate to the webview).
func (r *subscriptionResolver) ClustersWatch(ctx context.Context) (<-chan []*cluster.Cluster, error) {
	return r.ClusterSvc.Watch(ctx)
}

// ChatStream is the resolver for the chatStream field.
func (r *subscriptionResolver) ChatStream(ctx context.Context, input model.ChatInput) (<-chan *model.ChatChunk, error) {
	panic(fmt.Errorf("not implemented: ChatStream - chatStream"))
}

// AuthStateWatch is the resolver for the authStateWatch field. Emits the current
// auth-state snapshot, then a fresh snapshot on every sign-in / sign-out / refresh
// change. The auth-state stream is latest-value (current-on-subscribe), so its
// first value already seeds the current state — just map each State through.
func (r *subscriptionResolver) AuthStateWatch(ctx context.Context) (<-chan *auth.State, error) {
	states, cancel := r.Auth.Subscribe()
	return mapStream(ctx, states, cancel, func(s auth.State) *auth.State { return &s }), nil
}

// ClusterCache returns ClusterCacheResolver implementation.
func (r *Resolver) ClusterCache() ClusterCacheResolver { return &clusterCacheResolver{r} }

// ClusterPrincipal returns ClusterPrincipalResolver implementation.
func (r *Resolver) ClusterPrincipal() ClusterPrincipalResolver { return &clusterPrincipalResolver{r} }

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

type clusterCacheResolver struct{ *Resolver }
type clusterPrincipalResolver struct{ *Resolver }
type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
