// Shared proto contract for host(Rust) <-> sidecar(Go) gRPC auth control channel.
//
// This file is the single source of truth for the AuthService wire format,
// consumed by both the Go sidecar (via protoc, see sidecar/grpc/authpb) and
// the Rust host (via tonic-build, see src-tauri/build.rs). It deliberately
// sits at the repo root alongside poke.proto.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.0
// source: auth.proto

package authpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AuthService_StartLogin_FullMethodName     = "/auth.AuthService/StartLogin"
	AuthService_Logout_FullMethodName         = "/auth.AuthService/Logout"
	AuthService_AuthStateWatch_FullMethodName = "/auth.AuthService/AuthStateWatch"
)

// AuthServiceClient is the client API for AuthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AuthService is the host-internal control channel for the local-first identity
// session. It rides the same socket as GraphQL (h2c multiplexing) but is
// consumed only by the native host (the tray), never the webview — the webview
// keeps using the GraphQL authState/login/logout/authStateWatch surface. Both
// transports share the one auth.Service, so a sign-in via either is observed by
// both.
type AuthServiceClient interface {
	// StartLogin runs the synchronous setup phase (loopback bind + browser open)
	// and returns its result. The async sign-in tail — redirect exchange, verify,
	// persist — runs in the background; its completion is observed via
	// AuthStateWatch. Mirrors the GraphQL `login` mutation shape.
	StartLogin(ctx context.Context, in *StartLoginRequest, opts ...grpc.CallOption) (*StartLoginResponse, error)
	// Logout clears local credentials and revokes the refresh token
	// (fire-and-forget revocation). Mirrors the GraphQL `logout` mutation.
	Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*LogoutResponse, error)
	// AuthStateWatch streams the current AuthState immediately (latest-value:
	// current-on-subscribe), then a fresh snapshot on every session change.
	// Long-lived; ends on client cancel or sidecar shutdown.
	AuthStateWatch(ctx context.Context, in *AuthStateWatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AuthState], error)
}

type authServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthServiceClient(cc grpc.ClientConnInterface) AuthServiceClient {
	return &authServiceClient{cc}
}

func (c *authServiceClient) StartLogin(ctx context.Context, in *StartLoginRequest, opts ...grpc.CallOption) (*StartLoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartLoginResponse)
	err := c.cc.Invoke(ctx, AuthService_StartLogin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*LogoutResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LogoutResponse)
	err := c.cc.Invoke(ctx, AuthService_Logout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) AuthStateWatch(ctx context.Context, in *AuthStateWatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AuthState], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AuthService_ServiceDesc.Streams[0], AuthService_AuthStateWatch_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AuthStateWatchRequest, AuthState]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AuthService_AuthStateWatchClient = grpc.ServerStreamingClient[AuthState]

// AuthServiceServer is the server API for AuthService service.
// All implementations must embed UnimplementedAuthServiceServer
// for forward compatibility.
//
// AuthService is the host-internal control channel for the local-first identity
// session. It rides the same socket as GraphQL (h2c multiplexing) but is
// consumed only by the native host (the tray), never the webview — the webview
// keeps using the GraphQL authState/login/logout/authStateWatch surface. Both
// transports share the one auth.Service, so a sign-in via either is observed by
// both.
type AuthServiceServer interface {
	// StartLogin runs the synchronous setup phase (loopback bind + browser open)
	// and returns its result. The async sign-in tail — redirect exchange, verify,
	// persist — runs in the background; its completion is observed via
	// AuthStateWatch. Mirrors the GraphQL `login` mutation shape.
	StartLogin(context.Context, *StartLoginRequest) (*StartLoginResponse, error)
	// Logout clears local credentials and revokes the refresh token
	// (fire-and-forget revocation). Mirrors the GraphQL `logout` mutation.
	Logout(context.Context, *LogoutRequest) (*LogoutResponse, error)
	// AuthStateWatch streams the current AuthState immediately (latest-value:
	// current-on-subscribe), then a fresh snapshot on every session change.
	// Long-lived; ends on client cancel or sidecar shutdown.
	AuthStateWatch(*AuthStateWatchRequest, grpc.ServerStreamingServer[AuthState]) error
	mustEmbedUnimplementedAuthServiceServer()
}

// UnimplementedAuthServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAuthServiceServer struct{}

func (UnimplementedAuthServiceServer) StartLogin(context.Context, *StartLoginRequest) (*StartLoginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartLogin not implemented")
}
func (UnimplementedAuthServiceServer) Logout(context.Context, *LogoutRequest) (*LogoutResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Logout not implemented")
}
func (UnimplementedAuthServiceServer) AuthStateWatch(*AuthStateWatchRequest, grpc.ServerStreamingServer[AuthState]) error {
	return status.Error(codes.Unimplemented, "method AuthStateWatch not implemented")
}
func (UnimplementedAuthServiceServer) mustEmbedUnimplementedAuthServiceServer() {}
func (UnimplementedAuthServiceServer) testEmbeddedByValue()                     {}

// UnsafeAuthServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthServiceServer will
// result in compilation errors.
type UnsafeAuthServiceServer interface {
	mustEmbedUnimplementedAuthServiceServer()
}

func RegisterAuthServiceServer(s grpc.ServiceRegistrar, srv AuthServiceServer) {
	// If the following call panics, it indicates UnimplementedAuthServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AuthService_ServiceDesc, srv)
}

func _AuthService_StartLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).StartLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_StartLogin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).StartLogin(ctx, req.(*StartLoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_Logout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).Logout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_Logout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).Logout(ctx, req.(*LogoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_AuthStateWatch_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(AuthStateWatchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AuthServiceServer).AuthStateWatch(m, &grpc.GenericServerStream[AuthStateWatchRequest, AuthState]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AuthService_AuthStateWatchServer = grpc.ServerStreamingServer[AuthState]

// AuthService_ServiceDesc is the grpc.ServiceDesc for AuthService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuthService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "auth.AuthService",
	HandlerType: (*AuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartLogin",
			Handler:    _AuthService_StartLogin_Handler,
		},
		{
			MethodName: "Logout",
			Handler:    _AuthService_Logout_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "AuthStateWatch",
			Handler:       _AuthService_AuthStateWatch_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "auth.proto",
}
