// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
)

// Streaming chat chunk. `delta` is the next piece of assistant text; `done` is true on the final frame (delta may be empty).
type ChatChunk struct {
	Delta string `json:"delta"`
	Done  bool   `json:"done"`
}

type ChatInput struct {
	Messages []*ChatMessageInput `json:"messages"`
}

type ChatMessageInput struct {
	Role    string `json:"role"`
	Content string `json:"content"`
}

// Sync status of a single cluster being mirrored into the local cache.
type ClusterSyncStatus struct {
	// Kube-context name — the row identity.
	Context string `json:"context"`
	// Per-cluster sync lifecycle state.
	State ClusterSyncState `json:"state"`
	// Last sync error; empty string when healthy.
	LastError string `json:"lastError"`
	// Unix-millis of the last successful reconcile; 0 if never synced.
	LastSyncedAt int `json:"lastSyncedAt"`
	// Current download rate in bytes/sec; 0 when idle or offline.
	DownloadRateBps int `json:"downloadRateBps"`
}

type KubeConfigWatchEvent struct {
	Type   WatchEventType `json:"type"`
	Object *KubeConfig    `json:"object,omitempty"`
}

type Mutation struct {
}

type Query struct {
}

// User-scoped preferences synced through the kstack cloud. Today this is a single free-form `placeholder` string — extend as the product grows.
type Settings struct {
	Placeholder string `json:"placeholder"`
}

type Subscription struct {
}

// Connection/sync health of the always-on engine that owns the single upstream connection.
type SyncStatus struct {
	// Engine lifecycle state.
	State SyncState `json:"state"`
	// Last upstream error; empty string when healthy.
	LastError string `json:"lastError"`
	// Unix-millis of the last successful snapshot reconcile; 0 if never synced.
	LastSyncedAt int `json:"lastSyncedAt"`
	// Unix-millis of the next scheduled reconnect while in `backoff`; 0 otherwise.
	RetryAt int `json:"retryAt"`
}

type UpdateSettingsInput struct {
	Placeholder *string `json:"placeholder,omitempty"`
}

// Per-cluster sync lifecycle for the local-cache sync engine.
type ClusterSyncState string

const (
	// Queued; sync not started yet.
	ClusterSyncStatePending ClusterSyncState = "PENDING"
	// Actively downloading the cluster's resources into the local cache.
	ClusterSyncStateSyncing ClusterSyncState = "SYNCING"
	// Caught up; watching for incremental changes.
	ClusterSyncStateLive ClusterSyncState = "LIVE"
	// Retrying after an error.
	ClusterSyncStateBackoff ClusterSyncState = "BACKOFF"
	// Cluster unreachable.
	ClusterSyncStateOffline ClusterSyncState = "OFFLINE"
)

var AllClusterSyncState = []ClusterSyncState{
	ClusterSyncStatePending,
	ClusterSyncStateSyncing,
	ClusterSyncStateLive,
	ClusterSyncStateBackoff,
	ClusterSyncStateOffline,
}

func (e ClusterSyncState) IsValid() bool {
	switch e {
	case ClusterSyncStatePending, ClusterSyncStateSyncing, ClusterSyncStateLive, ClusterSyncStateBackoff, ClusterSyncStateOffline:
		return true
	}
	return false
}

func (e ClusterSyncState) String() string {
	return string(e)
}

func (e *ClusterSyncState) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ClusterSyncState(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ClusterSyncState", str)
	}
	return nil
}

func (e ClusterSyncState) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ClusterSyncState) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ClusterSyncState) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// Engine connection lifecycle.
type SyncState string

const (
	SyncStateConnecting SyncState = "CONNECTING"
	SyncStateLive       SyncState = "LIVE"
	SyncStateBackoff    SyncState = "BACKOFF"
	SyncStateOffline    SyncState = "OFFLINE"
)

var AllSyncState = []SyncState{
	SyncStateConnecting,
	SyncStateLive,
	SyncStateBackoff,
	SyncStateOffline,
}

func (e SyncState) IsValid() bool {
	switch e {
	case SyncStateConnecting, SyncStateLive, SyncStateBackoff, SyncStateOffline:
		return true
	}
	return false
}

func (e SyncState) String() string {
	return string(e)
}

func (e *SyncState) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SyncState(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SyncState", str)
	}
	return nil
}

func (e SyncState) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *SyncState) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e SyncState) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type WatchEventType string

const (
	WatchEventTypeAdded    WatchEventType = "ADDED"
	WatchEventTypeModified WatchEventType = "MODIFIED"
	WatchEventTypeDeleted  WatchEventType = "DELETED"
	WatchEventTypeBookmark WatchEventType = "BOOKMARK"
	WatchEventTypeError    WatchEventType = "ERROR"
)

var AllWatchEventType = []WatchEventType{
	WatchEventTypeAdded,
	WatchEventTypeModified,
	WatchEventTypeDeleted,
	WatchEventTypeBookmark,
	WatchEventTypeError,
}

func (e WatchEventType) IsValid() bool {
	switch e {
	case WatchEventTypeAdded, WatchEventTypeModified, WatchEventTypeDeleted, WatchEventTypeBookmark, WatchEventTypeError:
		return true
	}
	return false
}

func (e WatchEventType) String() string {
	return string(e)
}

func (e *WatchEventType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = WatchEventType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid WatchEventType", str)
	}
	return nil
}

func (e WatchEventType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *WatchEventType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e WatchEventType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
