// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

// Streaming chat chunk. `delta` is the next piece of assistant text; `done` is true on the final frame (delta may be empty).
type ChatChunk struct {
	Delta string `json:"delta"`
	Done  bool   `json:"done"`
}

type ChatInput struct {
	Messages []*ChatMessageInput `json:"messages"`
}

type ChatMessageInput struct {
	Role    string `json:"role"`
	Content string `json:"content"`
}

// The connecting principal's effective RBAC in one namespace (live
// SelfSubjectRulesReview). Namespace-scoped (the API has no all-namespaces form)
// and point-in-time — for UI/debugging, not authoritative for access decisions.
type ClusterPermissions struct {
	// The namespace these rules were evaluated for.
	Namespace string `json:"namespace"`
	// Allowed resource rules (verbs × apiGroups × resources).
	ResourceRules []*ResourceRule `json:"resourceRules"`
	// Allowed non-resource rules (verbs × URLs), e.g. /healthz.
	NonResourceRules []*NonResourceRule `json:"nonResourceRules"`
	// True if some authorizers couldn't be evaluated, so the rule set may be incomplete.
	Incomplete bool `json:"incomplete"`
}

type Mutation struct {
}

// A non-resource RBAC rule: the verbs the principal may use against non-resource URLs (e.g. /healthz).
type NonResourceRule struct {
	Verbs           []string `json:"verbs"`
	NonResourceUrls []string `json:"nonResourceUrls"`
}

type Query struct {
}

// A resource-scoped RBAC rule: the verbs the principal may use on the given apiGroups/resources (optionally narrowed to named instances).
type ResourceRule struct {
	Verbs     []string `json:"verbs"`
	APIGroups []string `json:"apiGroups"`
	Resources []string `json:"resources"`
	// Specific resource names this rule is restricted to; empty means all.
	ResourceNames []string `json:"resourceNames"`
}

type Subscription struct {
}
