// Shared proto contract for host(Rust) <-> sidecar(Go) gRPC resync control channel.
//
// This file is the single source of truth for the PokeService wire format,
// consumed by both the Go sidecar (via protoc, see sidecar/grpc/pokepb) and
// the Rust host (via tonic-build, see src-tauri/build.rs). It deliberately
// sits at the repo root alongside auth.proto.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.0
// source: poke.proto

package pokepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PokeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PokeRequest) Reset() {
	*x = PokeRequest{}
	mi := &file_poke_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PokeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PokeRequest) ProtoMessage() {}

func (x *PokeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_poke_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PokeRequest.ProtoReflect.Descriptor instead.
func (*PokeRequest) Descriptor() ([]byte, []int) {
	return file_poke_proto_rawDescGZIP(), []int{0}
}

type PokeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PokeResponse) Reset() {
	*x = PokeResponse{}
	mi := &file_poke_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PokeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PokeResponse) ProtoMessage() {}

func (x *PokeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_poke_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PokeResponse.ProtoReflect.Descriptor instead.
func (*PokeResponse) Descriptor() ([]byte, []int) {
	return file_poke_proto_rawDescGZIP(), []int{1}
}

var File_poke_proto protoreflect.FileDescriptor

const file_poke_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"poke.proto\x12\x04poke\"\r\n" +
	"\vPokeRequest\"\x0e\n" +
	"\fPokeResponse2<\n" +
	"\vPokeService\x12-\n" +
	"\x04Poke\x12\x11.poke.PokeRequest\x1a\x12.poke.PokeResponseB8Z6github.com/kubetail-org/kstack-app/sidecar/grpc/pokepbb\x06proto3"

var (
	file_poke_proto_rawDescOnce sync.Once
	file_poke_proto_rawDescData []byte
)

func file_poke_proto_rawDescGZIP() []byte {
	file_poke_proto_rawDescOnce.Do(func() {
		file_poke_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_poke_proto_rawDesc), len(file_poke_proto_rawDesc)))
	})
	return file_poke_proto_rawDescData
}

var file_poke_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_poke_proto_goTypes = []any{
	(*PokeRequest)(nil),  // 0: poke.PokeRequest
	(*PokeResponse)(nil), // 1: poke.PokeResponse
}
var file_poke_proto_depIdxs = []int32{
	0, // 0: poke.PokeService.Poke:input_type -> poke.PokeRequest
	1, // 1: poke.PokeService.Poke:output_type -> poke.PokeResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_poke_proto_init() }
func file_poke_proto_init() {
	if File_poke_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_poke_proto_rawDesc), len(file_poke_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_poke_proto_goTypes,
		DependencyIndexes: file_poke_proto_depIdxs,
		MessageInfos:      file_poke_proto_msgTypes,
	}.Build()
	File_poke_proto = out.File
	file_poke_proto_goTypes = nil
	file_poke_proto_depIdxs = nil
}
